GET http://localhost:5073/games

###
GET http://localhost:5073/games/1

###
POST  http://localhost:5073/games
Content-Type: application/json

{
    "name": "Red Dead Redemption",
    "genre": "adult",
    "price": 49.99,
    "releaseDate": "2016-05-30"
}

###
PUT   http://localhost:5073/games/5
Content-Type: application/json

{
    # "id": 1,
    "name": "Street Fighter V Trbo",
    "genre": "Fighting",
    "price": 19.99,
    "releaseDate": "1992-07-05"
}